language: node_js

os:
  - linux

before_script:
  - npm i @npm-wharf/shipwright@latest -g

script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - shipwright build image --repo=npmwharf --name=k8s-tickbot --tags lm,v_s,v,miv,ma

node_js:
  - "8"
